"""Generate a sandboxed per-test-coverage capture kit (design §6 win 3 support). `find_modes` needs a
per-test coverage artifact, and producing it means *running the project's test suite* — which executes
arbitrary code. stitchgraph must never do that (cardinal read-only). Instead this **generates a recipe**
the user (or their agent) runs **in their own jail**, emitting the canonical artifact
`{"format": "stitchgraph-coverage-v1", "tests": {"<test id>": ["<function id>", ...]}}`.

Per detected language it writes three interchangeable options — pick whatever fits human or LLM:
  1. **Docker** (Dockerfile + docker-compose.yml): fully isolated (no network, non-root, tmpfs, capped).
  2. **shell** (run_coverage.sh): for when you already have a sandbox / container / CI runner.
  3. **CI** snippet (in README): drop into GitHub Actions.
Only the inert JSON matrix leaves the sandbox; `find_modes` then runs pure math on it.

Turnkey since v3.49.0 (research/26, closing the LLM field review's setup-friction finding): Python,
Rust, Go, and JS/TS all ship runnable capture loops. The design insight that makes the converters
trivial: **the kit is generated by stitchgraph, and stitchgraph's index already holds every function's
span** — so each kit ships `spans.json` (per-file `(node id, start, end_line)` tables) and one
stdlib-only converter maps covered lines → innermost enclosing span → node-id-exact function ids, with
no language parser and no stitchgraph inside the sandbox. Java remains an honest template (JaCoCo
per-test attribution needs build-system integration a generated script can't do responsibly).
"""
from __future__ import annotations

import os
from typing import Any

from .model import NodeKind
from .store import Store

_EXT_LANG = {
    ".py": "python", ".js": "javascript", ".jsx": "javascript", ".ts": "javascript",
    ".tsx": "javascript", ".mjs": "javascript", ".cjs": "javascript",
    ".go": "go", ".rs": "rust", ".java": "java",
}


def detect_languages(store: Store) -> list[str]:
    """Languages present in the index, by file extension of the node ids (most common first)."""
    counts: dict[str, int] = {}
    for nid in store.all_node_ids():
        path = nid.split("::", 1)[0]
        ext = os.path.splitext(path)[1].lower()
        lang = _EXT_LANG.get(ext)
        if lang:
            counts[lang] = counts.get(lang, 0) + 1
    return [lang for lang, _ in sorted(counts.items(), key=lambda kv: -kv[1])]


# --- the Python converter: native .coverage contexts -> canonical JSON (turnkey) ---
_PY_CONVERTER = r'''#!/usr/bin/env python3
"""Convert coverage.py per-test contexts (.coverage) into the canonical stitchgraph artifact.
Runs INSIDE the sandbox after the suite. Maps covered lines -> functions via AST. No stitchgraph needed."""
import ast, os, json, sys
import coverage

SRC = sys.argv[1] if len(sys.argv) > 1 else "."
OUT = sys.argv[2] if len(sys.argv) > 2 else "coverage_modes.json"

def func_ranges(path):
    """(qualified_name, lineno, end_lineno) for every def, with class/function nesting qualified as
    Class.method / outer.inner — matching stitchgraph node ids (path::Class.method), so distinct
    same-named methods stay distinct instead of collapsing to one id."""
    try: tree = ast.parse(open(path, encoding="utf-8").read())
    except Exception: return []
    out = []
    def visit(node, prefix):
        for child in ast.iter_child_nodes(node):
            if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                qual = prefix + child.name
                out.append((qual, child.lineno, child.end_lineno or child.lineno))
                visit(child, qual + ".")
            elif isinstance(child, ast.ClassDef):
                visit(child, prefix + child.name + ".")
            else:
                visit(child, prefix)
    visit(tree, "")
    return out

cov = coverage.Coverage(); cov.load(); data = cov.get_data()
tests = {}
for f in data.measured_files():
    if not f.endswith(".py"): continue
    rel = os.path.relpath(f, SRC)      # always relative (SRC='.' → relative to cwd) for clean ids
    ranges = func_ranges(f)
    try: cbl = data.contexts_by_lineno(f)
    except Exception: continue
    for ln, ctxs in cbl.items():
        # attribute the line to the INNERMOST enclosing def only (smallest span), so a line inside
        # a nested function isn't also credited to its parent (which may not have executed).
        best = None
        for (name, lo, hi) in ranges:
            if lo <= ln <= hi and (best is None or (hi - lo) < (best[2] - best[1])):
                best = (name, lo, hi)
        if best is None: continue
        for c in ctxs:
            if "::" not in c: continue          # keep real pytest test ids only
            tests.setdefault(c, set()).add(f"{rel}::{best[0]}")
out = {"format": "stitchgraph-coverage-v1",
       "tests": {t: sorted(fs) for t, fs in tests.items()}}
if not out["tests"]:
    # a 0-test artifact is the confident-absence trap: fail LOUD, write nothing
    sys.exit("ERROR: 0 tests captured — no artifact written. Check that pytest-cov ran "
             "(--cov --cov-context=test) and that the suite has tests.")
json.dump(out, open(OUT, "w"), indent=0)
print(f"wrote {OUT}: {len(out['tests'])} tests, "
      f"{len({x for fs in out['tests'].values() for x in fs})} functions")
'''

_PY_RUN = r'''#!/usr/bin/env bash
# Run the test suite under per-test coverage, then emit the canonical artifact.
# Intended to run inside the sandbox (Docker service below, or your own jail/CI).
# Run FROM YOUR PROJECT ROOT; kit files resolve relative to this script itself.
set -euo pipefail
KIT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# --cov* are pytest-COV flags: without the plugin pytest exits before running
# a single test (self-audit 2026-07-07 finding: coverage+pytest alone produced
# a confidently-empty artifact), hence pytest-cov here and the guard below.
pip install --quiet coverage pytest pytest-cov 2>/dev/null || true
rm -f .coverage
# --cov-context=test tags coverage by the running test id
python -m pytest -p no:cacheprovider -q \
  --cov=. --cov-context=test || true      # keep going even if some tests fail
[ -f .coverage ] || { echo "no coverage data captured — is pytest-cov installed and the suite runnable?" >&2; exit 1; }
python "$KIT/to_canonical.py" . coverage_modes.json
echo "artifact ready: coverage_modes.json  (copy it out; run: stitchgraph find-modes coverage_modes.json)"
'''

# Placeholder run script for non-turnkey languages. A clean, self-contained TODO — NOT a mangled
# copy of the Python recipe (which would leave stray pytest/pip/converter lines; panel R277).
_TEMPLATE_RUN = r'''#!/usr/bin/env bash
# TEMPLATE — {lang} is not turnkey. Wire your per-test coverage tool here, then convert its output to
# the canonical stitchgraph-coverage-v1 artifact (see README.md). Run inside the sandbox / your jail.
# spans.json (shipped with this kit) maps any covered line to its node-id-exact enclosing function.
set -euo pipefail
# 1) run the test suite under per-test coverage with: {tool}
# 2) convert the per-test coverage into coverage_modes.json — keys = test ids, values = the function
#    ids each test executed (ids like path::Class.method, matching stitchgraph node ids; see README.md
#    "Canonical artifact format"). Emit {{"format": "stitchgraph-coverage-v1", "tests": {{...}}}}.
echo "TODO: implement {lang} per-test coverage capture -> coverage_modes.json (see README.md)" >&2
exit 1
'''

# --- the universal converter (Rust / Go / JS kits): line coverage + spans.json -> canonical JSON ---
# stdlib-only python3; python3 exists in the rust:*, golang:* and node:22 (non-slim) Debian bases.
_UNI_CONVERTER = r'''#!/usr/bin/env python3
"""Convert per-test coverage captures into the canonical stitchgraph artifact (research/26).
Runs INSIDE the sandbox after the capture loop. No stitchgraph and no language parser needed:
spans.json (generated from the stitchgraph index) maps covered lines to node-id-exact functions.

Usage: to_canonical.py <format> <covdata_dir> <spans.json> <out.json> <tests.txt>
formats: llvm-json (Rust cargo-llvm-cov export) | goprofile (go -coverprofile) | istanbul (jest/vitest)
covdata holds one capture per test named <i>.<ext>; line i+1 of tests.txt is that test's id."""
import json, os, sys

fmt, covdir, spans_path, out_path, tests_path = sys.argv[1:6]
spans = json.load(open(spans_path))
ROOT = os.getcwd()

def rel_of(path):
    p = os.path.normpath(path)
    if os.path.isabs(p):
        try: p = os.path.relpath(p, ROOT)
        except ValueError: return None
    p = p.replace(os.sep, "/")
    return None if p.startswith("..") else p

_skey_cache = {}
def span_key(rel):
    """spans.json keys are relative to the stitchgraph INDEX root; when the
    capture runs in a subdirectory (a Go module / JS package inside a
    monorepo), coverage paths lack that prefix — recover via a UNIQUE
    suffix match rather than silently attributing nothing."""
    if rel in spans: return rel
    if rel not in _skey_cache:
        hits = [k for k in spans if k.endswith("/" + rel)]
        _skey_cache[rel] = hits[0] if len(hits) == 1 else None
    return _skey_cache[rel]

def innermost(rel, line):
    """Innermost enclosing span, so a nested fn isn't also credited to its parent."""
    best = None
    key = span_key(rel)
    if key is None: return None
    for nid, lo, hi in spans.get(key, ()):
        if lo <= line <= hi and (best is None or (hi - lo) < (best[2] - best[1])):
            best = (nid, lo, hi)
    return best[0] if best else None

def lines_llvm(path):
    d = json.load(open(path))
    for f in d.get("data", [{}])[0].get("functions", []):
        # an executed function's ENTRY line is inside its own span — exact for our purpose
        if f.get("count", 0) > 0 and f.get("regions") and f.get("filenames"):
            yield f["filenames"][0], f["regions"][0][0]

def lines_go(path):
    module = ""
    if os.path.exists("go.mod"):
        for ln in open("go.mod"):
            if ln.startswith("module "):
                module = ln.split()[1].strip() + "/"
                break
    for ln in open(path):
        ln = ln.strip()
        if not ln or ln.startswith("mode:"): continue
        try:
            loc, _stmts, count = ln.rsplit(" ", 2)
            if int(count) == 0: continue
            fname, rng = loc.split(":", 1)
            if module and fname.startswith(module): fname = fname[len(module):]
            lo = int(rng.split(",")[0].split(".")[0])
            hi = int(rng.split(",")[1].split(".")[0])
        except ValueError:
            continue
        for line in range(lo, hi + 1):
            yield fname, line

def lines_istanbul(path):
    d = json.load(open(path))
    for fpath, entry in d.items():
        smap, s = entry.get("statementMap", {}), entry.get("s", {})
        for sid, cnt in s.items():
            if cnt and sid in smap:
                yield fpath, smap[sid]["start"]["line"]

parse = {"llvm-json": lines_llvm, "goprofile": lines_go, "istanbul": lines_istanbul}[fmt]
test_ids = [ln.rstrip("\n") for ln in open(tests_path)]
tests = {}
for name in sorted(os.listdir(covdir)):
    stem = name.split(".", 1)[0]
    if not stem.isdigit(): continue
    idx = int(stem)
    tid = test_ids[idx] if idx < len(test_ids) else name
    try:
        hit = set()
        for fpath, line in parse(os.path.join(covdir, name)):
            rel = rel_of(fpath)
            if rel is None: continue
            nid = innermost(rel, line)
            if nid: hit.add(nid)
    except Exception as exc:                       # one bad capture never kills the batch
        print(f"skip {name}: {exc}", file=sys.stderr); continue
    if hit: tests[tid] = sorted(hit)

if not tests:
    # a 0-test artifact is the confident-absence trap: fail LOUD, write nothing
    sys.exit("ERROR: 0 tests captured — no artifact written. Common causes: the capture "
             "loop produced no files in covdata/, or coverage paths do not match "
             "spans.json (run the capture from the directory stitchgraph indexed).")
json.dump({"format": "stitchgraph-coverage-v1", "tests": tests}, open(out_path, "w"), indent=0)
print(f"wrote {out_path}: {len(tests)} tests, "
      f"{len({x for v in tests.values() for x in v})} functions")
'''

_RS_RUN = r'''#!/usr/bin/env bash
# Turnkey Rust per-test coverage (research/26). One instrumented build, then each
# test costs one execution + one JSON export (~0.5 s measured on a real crate).
# Run FROM YOUR PROJECT ROOT; kit files resolve relative to this script itself.
set -uo pipefail
KIT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
command -v cargo-llvm-cov >/dev/null 2>&1 || cargo install cargo-llvm-cov
rm -rf covdata   # stale captures from a previous run would misattribute by index
mkdir -p covdata
# one instrumented build + test enumeration (unit + integration binaries)
cargo llvm-cov test --no-report -- --list 2>/dev/null | sed -n 's/: test$//p' | sort -u > tests.txt
[ -s tests.txt ] || { echo "no tests found" >&2; exit 1; }
i=0
while IFS= read -r t; do
  cargo llvm-cov clean --profraw-only >/dev/null 2>&1
  if cargo llvm-cov test --no-report -- --exact "$t" >/dev/null 2>&1; then
    cargo llvm-cov report --json --output-path "covdata/${i}.json" >/dev/null 2>&1 \
      || echo "skip (no report): $t" >&2
  else
    echo "skip (test run failed): $t" >&2
  fi
  i=$((i+1))
done < tests.txt
python3 "$KIT/to_canonical.py" llvm-json covdata "$KIT/spans.json" coverage_modes.json tests.txt || exit 1
echo "artifact ready: coverage_modes.json  (run: stitchgraph find-modes coverage_modes.json)"
'''

_GO_RUN = r'''#!/usr/bin/env bash
# Turnkey Go per-test coverage (research/26): enumerate tests per package, one
# -coverprofile per test, coverpkg across the whole module.
# Run FROM YOUR PROJECT ROOT; kit files resolve relative to this script itself.
set -uo pipefail
KIT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
rm -rf covdata   # stale captures from a previous run would misattribute by index
mkdir -p covdata
: > tests.txt
i=0
for pkg in $(go list ./... 2>/dev/null); do
  for t in $(go test -list '.*' "$pkg" 2>/dev/null | grep -E '^(Test|Fuzz|Example)'); do
    go test -run "^${t}\$" -coverprofile="covdata/${i}.out" -coverpkg=./... "$pkg" >/dev/null 2>&1 \
      || echo "skip (test run failed): $pkg $t" >&2
    echo "${pkg}::${t}" >> tests.txt
    i=$((i+1))
  done
done
[ -s tests.txt ] || { echo "no tests found" >&2; exit 1; }
python3 "$KIT/to_canonical.py" goprofile covdata "$KIT/spans.json" coverage_modes.json tests.txt || exit 1
echo "artifact ready: coverage_modes.json  (run: stitchgraph find-modes coverage_modes.json)"
'''

_JS_RUN = r'''#!/usr/bin/env bash
# Turnkey JS/TS coverage (research/26). Granularity is per test FILE — istanbul
# per-test contexts are runner-specific, per-file is what generalizes across
# jest and vitest (documented in README).
# Run FROM YOUR PROJECT ROOT; kit files resolve relative to this script itself.
set -uo pipefail
KIT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
rm -rf covdata   # stale captures from a previous run would misattribute by index
mkdir -p covdata
: > tests.txt
# strip $PWD/ with parameter expansion, NOT sed — a cwd containing sed
# metacharacters ('|', '[', '.') would break or silently skip the strip
relpaths() { while IFS= read -r p; do printf '%s\n' "${p#"$PWD"/}"; done; }
if [ -f package.json ] && grep -q '"vitest"' package.json; then
  npx vitest list --filesOnly 2>/dev/null | relpaths | grep -v '^$' > tests.txt || true
  # "$PWD/$1" pins the filter to the exact file — a bare relative path is a
  # SUBSTRING filter in vitest and would also run e.g. web<path> lookalikes
  RUN() { npx vitest run --coverage.enabled --coverage.provider=v8 \
          --coverage.reporter=json --coverage.reportsDirectory=covtmp "$PWD/$1"; }
elif [ -f package.json ] && grep -q '"jest"' package.json; then
  npx jest --listTests 2>/dev/null | relpaths | grep -v '^$' > tests.txt || true
  # --runTestsByPath: exact path, not an unanchored testPathPattern REGEX
  RUN() { npx jest --coverage --coverageReporters=json --coverageDirectory=covtmp \
          --runTestsByPath "$1"; }
else
  echo "no jest/vitest in package.json — wire your runner in this script (see README)" >&2
  exit 1
fi
[ -s tests.txt ] || { echo "no test files found (jest needs --listTests; vitest needs a version with 'vitest list', v3+ — wire enumeration manually above if older)" >&2; exit 1; }
i=0
while IFS= read -r f; do
  rm -rf covtmp
  if RUN "$f" >/dev/null 2>&1 && [ -f covtmp/coverage-final.json ]; then
    cp covtmp/coverage-final.json "covdata/${i}.json"
  else
    echo "skip (run failed): $f" >&2
  fi
  i=$((i+1))
done < tests.txt
python3 "$KIT/to_canonical.py" istanbul covdata "$KIT/spans.json" coverage_modes.json tests.txt || exit 1
echo "artifact ready: coverage_modes.json  (run: stitchgraph find-modes coverage_modes.json)"
'''

_DOCKERFILE = """# Sandboxed per-test coverage capture. Build/run this in YOUR environment; it executes the
# project's tests in an isolated, non-root, network-less container. Only coverage_modes.json leaves.
# Dependencies install at BUILD time (network available) so the RUN stays network-less; the build
# context is the PROJECT ROOT (docker-compose.yml sets it) so the whole project is copied in.
FROM {base}
WORKDIR /work
COPY . /work
{deps}RUN useradd -m runner || true
RUN chown -R runner /work
USER runner
CMD ["bash", "{kp}run_coverage.sh"]
"""

_COMPOSE = """# `docker compose run --rm coverage` — isolated: no network at RUN time (dependencies are
# baked at build time, where network exists), non-root, dropped caps, memory/pid limits. The
# container filesystem stays writable — the capture writes build artifacts into the project
# copy — but the container is disposable (--rm) and unprivileged. Emits ./out/coverage_modes.json.
# Assumes this kit directory sits INSIDE the project; if you moved it, fix context/paths below.
services:
  coverage:
    build:
      context: {ctx}
      dockerfile: {kp}Dockerfile
    network_mode: "none"          # no outbound network while running untrusted tests
    tmpfs:
      - /tmp
    cap_drop: ["ALL"]
    security_opt: ["no-new-privileges:true"]
    pids_limit: 512
    mem_limit: 2g
    volumes:
      - ./out:/work/{kp}out       # the ONLY thing that comes back out
    command: bash -lc "bash {kp}run_coverage.sh && cp coverage_modes.json {kp}out/"
"""

_LANG: dict[str, dict[str, Any]] = {
    # deps run at image-BUILD time (network exists there; the compose service runs with
    # network_mode "none") and best-effort install the project's own dependencies too —
    # a runtime fetch (go mod / npm / rustup) inside the network-less container would fail.
    "python": {"base": "python:3.12-slim",
               "deps": ("RUN pip install --no-cache-dir coverage pytest pytest-cov\n"
                        "RUN pip install --no-cache-dir -e . 2>/dev/null || "
                        "pip install --no-cache-dir -r requirements.txt 2>/dev/null || true\n"),
               "tool": "coverage.py (`pytest --cov --cov-context=test`, needs pytest-cov)",
               "run": _PY_RUN, "converter": ("to_canonical.py", _PY_CONVERTER),
               "note": None},
    # node:22 (non-slim) deliberately: the universal converter is stdlib python3,
    # present in the full Debian bases but not in -slim node images.
    "javascript": {"base": "node:22",
                   "deps": "RUN npm ci 2>/dev/null || npm install 2>/dev/null || true\n",
                   "tool": "jest or vitest with istanbul JSON coverage, one run per test file",
                   "run": _JS_RUN, "converter": ("to_canonical.py", _UNI_CONVERTER),
                   "note": ("granularity is per test FILE, not per test function — "
                            "istanbul per-test contexts are runner-specific; per-file "
                            "generalizes across jest and vitest")},
    "go": {"base": "golang:1.24",
           "deps": "RUN go mod download 2>/dev/null || true\n",
           "tool": "`go test -run '^<Test>$' -coverprofile -coverpkg=./...` per test",
           "run": _GO_RUN, "converter": ("to_canonical.py", _UNI_CONVERTER),
           "note": None},
    "rust": {"base": "rust:1",
             "deps": ("RUN cargo install cargo-llvm-cov 2>/dev/null || true\n"
                      "RUN rustup component add llvm-tools-preview 2>/dev/null || true\n"
                      "RUN cargo fetch 2>/dev/null || true\n"),
             "tool": "cargo-llvm-cov (one instrumented build, then per-test profraw + JSON export)",
             "run": _RS_RUN, "converter": ("to_canonical.py", _UNI_CONVERTER),
             "note": None},
    "java": {"base": "eclipse-temurin:21", "deps": "",
             "tool": "JaCoCo (per-test: the jacoco agent with a per-test session id)",
             "run": None, "converter": None, "note": None},
}

# language -> source extensions whose function spans go into the kit's spans.json
_LANG_EXTS: dict[str, set[str]] = {}
for _ext, _lang in _EXT_LANG.items():
    _LANG_EXTS.setdefault(_lang, set()).add(_ext)


def _spans(store: Store, exts: set[str]) -> dict[str, list[list]]:
    """Per-file `(node id, start line, end line)` span tables for the kit's
    spans.json — the research/26 insight: stitchgraph generated this kit, and
    its index already knows every function's span, so the sandbox-side
    converter needs no language parser and emits node-id-EXACT function ids."""
    out: dict[str, list[list]] = {}
    for node in store.all_nodes_full():
        if node.kind not in (NodeKind.FUNCTION, NodeKind.METHOD, NodeKind.TEST):
            continue
        rel = node.id.split("::", 1)[0]
        if os.path.splitext(rel)[1].lower() not in exts:
            continue
        parts = node.location.rsplit(":", 2)
        if len(parts) != 3 or not parts[1].isdigit():
            continue
        start = int(parts[1])
        end = node.end_line if isinstance(node.end_line, int) \
            and node.end_line >= start else start
        out.setdefault(rel, []).append([node.id, start, end])
    for entries in out.values():
        entries.sort(key=lambda e: e[1])
    return out


def _readme(lang: str, info: dict[str, Any], kp: str = "") -> str:
    turnkey = info["run"] is not None
    runpath = f"{kp}run_coverage.sh" if kp else "run_coverage.sh"
    return f"""# stitchgraph per-test coverage kit — {lang}

`find_modes` needs a **per-test coverage artifact**: which test executed which function. Producing it
means *running this project's test suite*, which runs arbitrary code — so do it in a **sandbox**, never
on your host. This kit gives three interchangeable ways to produce the canonical artifact
`coverage_modes.json`. stitchgraph did NOT run anything to make this kit — you run it, jailed.

Coverage tool for {lang}: **{info['tool']}**

## Option 1 — Docker (most isolated; recommended)
Run from this kit directory (dependencies bake at build time; the run itself has no network):
```
docker compose run --rm coverage        # no network at run time, non-root, capped
# → ./out/coverage_modes.json
```

## Option 2 — plain shell (if you already have a sandbox / CI runner / devcontainer)
Run **from the project root** (the directory stitchgraph indexed) — the script finds its own
kit files (`to_canonical.py`, `spans.json`) relative to itself:
```
bash {runpath}                     # → coverage_modes.json in the project root
```

## Option 3 — CI (GitHub Actions)
```yaml
- run: bash {runpath}
- uses: actions/upload-artifact@v4
  with: {{ name: coverage_modes, path: coverage_modes.json }}
```

## Then, back on your machine (no code execution — pure math):
```
stitchgraph find-modes coverage_modes.json      # behavioural modes, dimensionality, minimal test set
```

## Canonical artifact format (`stitchgraph-coverage-v1`)
```json
{{
  "format": "stitchgraph-coverage-v1",
  "tests": {{
    "tests/test_x.py::test_a": ["src/pkg/mod.py::func1", "src/pkg/mod.py::Class.method"],
    "...": ["..."]
  }}
}}
```
Keys = test ids; values = the functions that test executed (ids like `path::qualified.name`, matching
stitchgraph's node ids so `find_modes` can label modes by module). Any per-test coverage tool that can
emit this works. Keys are opaque labels — some tools suffix a phase (coverage.py's `--cov-context=test`
emits e.g. `tests/test_x.py::test_a|run`); that is fine, only the function-id *values* must match node ids.

## spans.json (shipped with this kit)
Per-file `[node id, start line, end line]` tables generated from the stitchgraph index. The converter
maps any covered line to its innermost enclosing span — no language parser needed in the sandbox, and
the emitted function ids match stitchgraph node ids exactly. Regenerate the kit after large refactors
so the spans stay current.
""" + (f"""
## NOTE — {lang} granularity
{info['note']}.
""" if info.get("note") else "") + ("" if turnkey else f"""
## NOTE — {lang} is a TEMPLATE, not turnkey
Python/Rust/Go/JS ship complete capture loops; for {lang}, wire `{info['tool']}` in `run_coverage.sh`
to run the suite with per-test attribution, then convert its output to the canonical format above —
spans.json makes the line→function mapping a trivial lookup. An LLM agent can complete it from this
spec.
""")


def generate(store: Store, out_dir: str, language: str | None = None) -> dict[str, Any]:
    """Write the capture kit(s) into `out_dir`. Returns a manifest {languages, files, out_dir}.
    Writes helper files only (like `report`) — never touches project source, never executes."""
    langs = [language] if language else detect_languages(store)
    langs = [x for x in langs if x in _LANG] or ["python"]
    written: list[str] = []
    for lang in langs:
        info = _LANG[lang]
        d = os.path.join(out_dir, lang) if len(langs) > 1 else out_dir
        os.makedirs(os.path.join(d, "out"), exist_ok=True)
        # Docker option: build context = the PROJECT ROOT so `COPY . /work` copies the
        # project, not just this kit (self-audit 2026-07-07 — kit-as-context shipped a
        # container with no code in it). The kit's location inside the project is only
        # knowable when out_dir stays under the cwd the kit was generated from (the
        # default `stitchgraph-coverage/`); a kit generated elsewhere falls back to
        # kit-dir context and the compose header comment says what to fix.
        kitrel = os.path.relpath(os.path.abspath(d), os.getcwd()).replace(os.sep, "/")
        inside = kitrel != ".." and not kitrel.startswith("../") and kitrel != "."
        kp = f"{kitrel}/" if inside else ""
        ctx = os.path.relpath(os.getcwd(), os.path.abspath(d)) if inside else "."
        files = {
            "Dockerfile": _DOCKERFILE.format(base=info["base"], deps=info["deps"], kp=kp),
            "docker-compose.yml": _COMPOSE.format(ctx=ctx, kp=kp),
            "run_coverage.sh": info["run"] or _TEMPLATE_RUN.format(lang=lang, tool=info["tool"]),
            "README.md": _readme(lang, info, kp),
        }
        if info["converter"]:
            cname, ctext = info["converter"]
            files[cname] = ctext
        import json as _json
        files["spans.json"] = _json.dumps(
            _spans(store, _LANG_EXTS.get(lang, set())), indent=0)
        for name, text in files.items():
            p = os.path.join(d, name)
            with open(p, "w", encoding="utf-8") as fh:
                fh.write(text)
            written.append(p)
    return {"languages": langs, "files": written, "out_dir": out_dir,
            "turnkey": [x for x in langs if _LANG[x]["run"] is not None]}
